# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b4e978a0e8e3d64b1b7e1f9e7fcb22b86906b05c3e1966ef35e9535bdb43f96dce9fabe6f5058754de5f8be76648b8f6bd4d11f77b97e12afc62a8896144a0e

test:
  secret_key_base: 9696d7efaeb0334b42991543f92eb52852f883b2dace7a32f6883d75742c020d439159cdd34463f2656b5c2fdb7fa213eb36e8573daea122d50152bd1615f78e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
